services:

  postgres:
    image: postgres:latest
    container_name: database-container
    ports:
      - "5433:5432"
    env_file:
      - postgres.env
    networks:
      - app_network

  url-shortener:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: url-shortener
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - STORAGE=cache
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network: